#!/bin/bash
#assumption: with np=1
if [ -z $contained ]
then
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/arpack-ng-3.1.5/lib64/
fi
valgrind -v --tool=memcheck --leak-check=yes --track-origins=yes --num-callers=20 --gen-suppressions=yes dd_alpha_amg_db $2
